<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Variable.Identity/Variable.Identity.csproj" />
    <ProjectReference Include="../Variable.Authoring/Variable.Authoring.csproj" />
    <EmbeddedResource Include="Persistence/Migrations/*.sql" />
  </ItemGroup>
</Project>
